### ISSUE TITLE
Full text requirement

### ISSUE THREAD

**Issue by tuantran23012000** [cxh0519/VTB#1]
Can you provide publish version of your article?

**Comment by cxh0519** [comment]
Thanks for your interest in our work, please leave your email address and the PDF will be sent to you.

**Comment by tuantran23012000** [comment]
> 
Thanks for your response, my gmail: trananhtuan23012000@gmail.com.

**Comment by rose-jinyang** [comment]
Hello @cxh0519 
How are you?
Thanks for contributing to this project.
Can I get your paper for this project?
My email: samkmi80@gmail.com
Thanks

**Comment by rose-jinyang** [comment]
Hi @tuantran23012000
How are you?
Did you get the paper for this project?
If so, could you share it with me?
Thanks

**Comment by tuantran23012000** [comment]
Hi,
I sent to you. Pls check your mail.

Vào Th 4, 7 thg 8, 2024 lúc 14:37 rose-jinyang ***@***.***>
đã viết:

**Comment by rose-jinyang** [comment]
Very thank you @tuantran23012000
