### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by AbdullahNasser98** [cxh0519/VTB#5]
Just wondering if there is any code published for inference yet.

**Comment by cxh0519** [comment]
The test results are reported during the training stage. More specifically, the 'args.valid_split' in train.py is defined as 'test' in config.py. Therefore, the 'valid_results' in train.py are actually the test results.

**Comment by AbdullahNasser98** [comment]
I know.
But if I want to use the model in production without having to train the model over and over again what should I do?

**Comment by cxh0519** [comment]
We have not provided the inference code due to the train.py is easy to be modified.
Once you have a trained model in ckpt format, you can test its performance by simply loading it and running the valid codes only.

**Comment by AbdullahNasser98** [comment]
Yes that is ture.
But when ever I try to use the trained model for validation i get this error
`KeyError: 'vis_embed'`

**Comment by AbdullahNasser98** [comment]
Some layers that are trained are not saved when you call the
`torch.save` function
Do you have any insight as to why?

**Comment by AbdullahNasser98** [comment]
I solved the issue.
But I have a request, could you please give me access to the paper?

**Comment by cxh0519** [comment]
Please leave your email address and I will send the paper to you.

**Comment by AbdullahNasser98** [comment]
abdullah.nasser2597@gmail.com

And thanks a lot.
